### PR TITLE
Fix installation

### PR DESCRIPTION
**Pull request by Midnighter**
I have successfully installed and run the platform on multiple hosts. Please give it a try @phantomas1234.

* Please read the **new instructions** carefully since I have moved to a make system.
* You can now install partially in parallel using `make -j` \o/

Let me know what works/doesn't work for you.

### CODE REVIEW

**Review by phantomas1234 — CHANGES_REQUESTED** [review]
Did I ask for this :-) I am also not sure how much I can trust this after all those changes. On the other hand its nice.

First of all, it doesn't actually work on my mac:
`➜  caffeine-bootstrap git:(fix-installation) make install
Building design-storage...
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
/bin/sh: line 0: cd: design-storage: No such file or directory
/Library/Developer/CommandLineTools/usr/bin/make -C design-storage build-travis
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
make: *** design-storage: No such file or directory.  Stop.
make: *** [.build/design-storage] Error 2`


Please move location of cplex back to just `modeling-base` (why the extra cameo directory?). Also, please provide an empty `modeling-base` directory so that the user does not need to create it.```
`make` check does not check for cplex, please fix. Also output looks like this:
`./scripts/check.sh
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
bash: ok
git: ok
docker: ok
docker-compose: ok`.

**Comment by Midnighter** [comment]
Seems to be some difference between the `date` command line tool on Linux and Mac. I hate that they are different.

The caffeine build is now using the same git repo as we do for modeling-base that's why I made those changes. The directory is created by git and must not already exist. I have adjusted that image to incorporate CPLEX in a similar way from an outside file. I can certainly provide a different directory where CPLEX should be placed and simply copy it to the correct destination.

**Comment by phantomas1234** [comment]
> Seems to be some difference between the date command line tool on Linux and Mac. I hate that they are different.
Please fix anyhow. This repo is supposed to work on any kind of platform (which it did before) not just linux.

Fine with the directory (`modeling-base/cameo`) as long as you create it for the user.

Let me know if you can still do this.

**Comment by Midnighter** [comment]
I think it should be ready now. Place CPLEX in `cplex/` and start over from `make check`. Hope it works on Mac now :crossed_fingers:

**Pull request merged**
